### PR TITLE
JB's changes, v4 update

### PR DESCRIPTION
**Pull request by dmjio**
cc @jb55 @jhickner

@jhickner, I assume your fork was to add v4 support. I believe @jb55 has already done this.

### CODE REVIEW

**Comment by dmjio** [comment]
@jb55 is this ready for a merge you'd say?

**Comment by jb55** [comment]
uhh maybe not "release" ready, I only tested that the signature matched their tutorial example. I was going to test it in an app I was building, but I didn't get around to that yet.

**Comment by jb55** [comment]
also some of my TODO lines need to be tended to before this is committed (I temporarily needed PackageImports with my dev env setup)

**Comment by dmjio** [comment]
@jb55, hey, was wondering, can this be merged now? :) great work btw.

**Comment by jb55** [comment]
oh darn I completely forgot about this, it was part of some contract work that was abandoned :[

I'll try to find an excuse to revive it soon...

**Comment by dmjio** [comment]
@jb55 Sorry, the derivation is far more borked than I realized. Should be:

```nix
{ compiler ? "ghc802" }:                                                                                                                                                                                                                      
  let                                                                                                                                                                                                                                         
   config = {                                                                                                                                                                                                                                 
     packageOverrides = pkgs: with pkgs.haskell.lib; {                                                                                                                                                                                        
       haskell = pkgs.haskell // {                                                                                                                                                                                                            
         packages = pkgs.haskell.packages // {                                                                                                                                                                                                
            ${compiler} = pkgs.haskell.packages.${compiler}.override {                                                                                                                                                                        
              overrides = self: super: rec {                                                                                                                                                                                                  
                s3-signer = buildStrictly (self.callPackage ./s3-signer.nix { });                                                                                                                                                             
              };                                                                                                                                                                                                                              
           };                                                                                                                                                                                                                                 
         };                                                                                                                                                                                                                                   
      };                                                                                                                                                                                                                                      
   };                                                                                                                                                                                                                                         
};                                                                                                                                                                                                                                            
in                                                                                                                                                                                                                                            
  let                                                                                                                                                                                                                                         
    pkgs = import <nixpkgs> { inherit config; };                                                                                                                                                                                              
    s3-signer = pkgs.haskell.packages.${compiler}.s3-signer;                                                                                                                                                                                  
  in { inherit s3-signer; }  
```

**Comment by dmjio** [comment]
I'll merge it, no worries.

**Comment by dmjio** [comment]
🍺 great work!

**Comment by jb55** [comment]
it might need a few more patches for older version compatibility...

**Comment by jb55** [comment]
and I just realized the test I had wasn't really testing anything... I'll do those as separate PRs

**Comment by jb55** [comment]
I'll fix nix build and test in a new PR so don't worry about that

**Comment by dmjio** [comment]
k, sounds good thanks. Feel free to add your name in the cabal file.

**Pull request merged**
